db:
  jdbcUrl: 'jdbc:postgresql://localhost:5432/postgres'
  username: 'postgres'
  password: 'postgres'
  driverClassName: 'org.postgresql.Driver'
  minimumIdle: 5
  maximumPoolSize: 10
  connectionTimeout: 10000
  validationTimeout: 5000
  connectionTestQuery: 'SELECT 1'

management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

  endpoints:
    web:
      exposure:
        include: "info,health"