apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.backend.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "spring-boot-helm:{{ .Values.backend.deployment.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: http
            initialDelaySeconds: 1
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: http
            initialDelaySeconds: 1
            periodSeconds: 5
          volumeMounts:
            - mountPath: /config/application.yml
              subPath: application.yml
              name: backend-config
      volumes:
        - name: backend-config
          configMap:
            name: {{ .Release.Name }}-configmap